steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - crock_csv_generator 
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python38
  - --allow-unauthenticated
  